dist: trusty
language: python
python:
  - "3.4"
before_install:
  - export BOTO_CONFIG=/dev/null
install:
  - pip install -r requirements.txt .
  - python -m nltk.downloader "punkt"
  - python -m nltk.downloader "averaged_perceptron_tagger"
  - python -m nltk.downloader "maxent_ne_chunker"
  - python -m nltk.downloader "words"
script:
  - python setup.py test